remote_theme: pmarsceill/just-the-docs
# Aux links for the upper right navigation
aux_links:
  "Project ES/GS 2020-2021 op GitHub":
    - "//github.com/Project-ES-20-21/"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
ga_tracking: G-HM7E4D1KWL
